### ISSUE TITLE
Not responding after resume from suspend

### ISSUE THREAD

**Issue by cdfa** [aclysma/skulpin#81] opened 2020-11-29 23:16 UTC
Hi, I orginally reported this at [neovide](https://github.com/Kethku/neovide/issues/393), but the author said it would probably be an upstream issue.

I'm having a weird issue where Neovide does not respond anymore after my laptop resumes from sleep. I'm happy to help debugging, but I don't really know where to start.

Some basic info:
Neovide version: 0.6.0.r32.g0203d02 (skulpin version does not seem to be pinned, but I'm no Rust expert)
`uname -or`: 5.4.80-1-MANJARO GNU/Linux

**Comment by cdfa** [comment] 2020-11-30 11:44
I tried the interactive_sdl2 example from this repo and it happens there too. Here's a log:
```
[2020-11-30T11:40:17Z INFO  interactive_sdl2] Window { timestamp: 663026, window_id: 2, win_event: Leave }
[2020-11-30T11:40:31Z INFO  interactive_sdl2] Window { timestamp: 676974, window_id: 2, win_event: FocusLost }
[2020-11-30T11:40:45Z INFO  interactive_sdl2] Unknown { timestamp: 690245, type_: 772 }
[2020-11-30T11:40:46Z INFO  interactive_sdl2] Unknown { timestamp: 691776, type_: 772 }
[2020-11-30T11:40:49Z INFO  interactive_sdl2] Window { timestamp: 694244, window_id: 2, win_event: FocusGained }
[2020-11-30T11:40:49Z INFO  interactive_sdl2] Window { timestamp: 694244, window_id: 2, win_event: TakeFocus }
[2020-11-30T11:40:49Z INFO  interactive_sdl2] Window { timestamp: 694640, window_id: 2, win_event: Exposed }
[2020-11-30T11:41:25Z INFO  interactive_sdl2] Window { timestamp: 730450, window_id: 2, win_event: Exposed }
```

**Comment by aclysma** [comment] 2020-12-07 05:56
Does this reproduce when using a winit example? If the window is stuck and no input is coming in, that's probably an SDL2 issue. You could probably strip out some stuff from the example to test.

If you resize the window, that should restart a lot of the GPU side of things so that may be worth trying to see what happens. (I'm not sure if the process is still running but the rendering is stuck, or if the process is just not getting input.)

**Comment by cdfa** [comment] 2020-12-12 11:45
Yes, the same happens with the winit example. Something that might be interesting is that the SDL example blocks compositing, but the winit one doesn't.

Resizing the window doesn't fix it. I get "old renders" of my window border in the new extra space.

**Comment by aclysma** [comment] 2020-12-13 15:19
This didn't reproduce on my laptop (macOS). I'll try reproducing on a windows desktop, I don't have a linux machine to try this on. If it doesn't reproduce for me, I think the next step would be adding lots of trace logging and getting a new log.

**Comment by cdfa** [comment] 2021-01-21 11:43
Any progress on this?

**Comment by aclysma** [comment] 2021-01-21 14:25
I was unable to reproduce it. The next step I have in mind would be to either use a debugger or printlns to track down what lines of code are being hit after resuming from suspend.

I'm working on a new graphics API and hopefully will have a 0.1 release of it in the next few weeks. Afterwards, I plan to migrate skulpin to use it (should be a quick change). If the problem remains after that, I can make a custom branch or something that has more logging to try to track this down.

Or, if you can add logging yourself, or maybe even attach a debugger and hit pause and get a stack trace, then it might be enough information to fix it now.

**Comment by cdfa** [comment] 2021-01-21 18:51
Alright, it's not a pressing issue for me at the moment since I don't use neovide anymore, so I'll wait and see if the new graphics API fixes it. I've tried using a debugger with Rust before, but I would only get machine instruction, no Rust code. Adding printlns should be doable though.

**Comment by aclysma** [comment] 2021-03-14 04:36
Wanted to mention that 0.12 is published now and using the new rendering backend. Would be curious to know if the issue still occurs. (If it does, we can try a minimal example in the rafx crate to track it down.)

**Comment by cdfa** [comment] 2021-03-14 20:53
I'm getting a build error on latest master (`5287f2a5a95c1df06d44be30b53bb35332ed8666`):

<details>
<summary>Log</summary>

```
$ git pull
...
$ cargo run --example interactive_sdl2
...
Compiling skia-bindings v0.38.2
error[E0308]: mismatched types
--> /home/cdfa/.cargo/registry/src/github.com-1ecc6299db9ec823/rafx-api-0.0.10/src/backends/vulkan/device_context.rs:149:13
|
149 |             physical_device,
|             ^^^^^^^^^^^^^^^ expected struct `ash::vk::definitions::PhysicalDevice`, found struct `PhysicalDevice`
|
= note: perhaps two different versions of crate `ash` are being used?

error[E0308]: mismatched types
--> /home/cdfa/.cargo/registry/src/github.com-1ecc6299db9ec823/rafx-api-0.0.10/src/backends/vulkan/device_context.rs:150:21
|
150 |             device: logical_device.clone(),
|                     ^^^^^^^^^^^^^^^^^^^^^^ expected struct `ash::device::Device`, found struct `entry::ash::Device`
|
= note: perhaps two different versions of crate `ash` are being used?

error[E0308]: mismatched types
--> /home/cdfa/.cargo/registry/src/github.com-1ecc6299db9ec823/rafx-api-0.0.10/src/backends/vulkan/device_context.rs:151:23
|
151 |             instance: instance.instance.clone(),
|                       ^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `ash::instance::Instance`, found struct `entry::ash::Instance`
|
= note: perhaps two different versions of crate `ash` are being used?

error[E0308]: mismatched types
--> /home/cdfa/.cargo/registry/src/github.com-1ecc6299db9ec823/rafx-api-0.0.10/src/backends/vulkan/texture.rs:29:32
|
29 |                 .destroy_image(self.image, &allocation)
|                                ^^^^^^^^^^ expected struct `ash::vk::definitions::Image`, found struct `Image`
|
= note: perhaps two different versions of crate `ash` are being used?

error[E0308]: mismatched types
--> /home/cdfa/.cargo/registry/src/github.com-1ecc6299db9ec823/rafx-api-0.0.10/src/backends/vulkan/texture.rs:294:33
|
294 |                 required_flags: vk::MemoryPropertyFlags::empty(),
|                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `ash::vk::bitflags::MemoryPropertyFlags`, found struct `MemoryPropertyFlags`
|
= note: perhaps two different versions of crate `ash` are being used?

error[E0308]: mismatched types
--> /home/cdfa/.cargo/registry/src/github.com-1ecc6299db9ec823/rafx-api-0.0.10/src/backends/vulkan/texture.rs:295:34
|
295 |                 preferred_flags: vk::MemoryPropertyFlags::empty(),
|                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `ash::vk::bitflags::MemoryPropertyFlags`, found struct `MemoryPropertyFlags`
|
= note: perhaps two different versions of crate `ash` are being used?

error[E0308]: mismatched types
--> /home/cdfa/.cargo/registry/src/github.com-1ecc6299db9ec823/rafx-api-0.0.10/src/backends/vulkan/texture.rs:323:31
|
323 |                 .create_image(&image_create_info, &allocation_create_info)
|                               ^^^^^^^^^^^^^^^^^^ expected struct `ash::vk::definitions::ImageCreateInfo`, found struct `ImageCreateInfoBuilder`
|
= note: expected reference `&ash::vk::definitions::ImageCreateInfo`
found reference `&ImageCreateInfoBuilder<'_>`

error[E0308]: mismatched types
--> /home/cdfa/.cargo/registry/src/github.com-1ecc6299db9ec823/rafx-api-0.0.10/src/backends/vulkan/texture.rs:330:17
|
330 |                 image,
|                 ^^^^^ expected struct `Image`, found struct `ash::vk::definitions::Image`
|
= note: perhaps two different versions of crate `ash` are being used?

error[E0308]: mismatched types
--> /home/cdfa/.cargo/registry/src/github.com-1ecc6299db9ec823/rafx-api-0.0.10/src/backends/vulkan/buffer.rs:144:29
|
144 |             required_flags: vk::MemoryPropertyFlags::empty(),
|                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `ash::vk::bitflags::MemoryPropertyFlags`, found struct `MemoryPropertyFlags`
|
= note: perhaps two different versions of crate `ash` are being used?

error[E0308]: mismatched types
--> /home/cdfa/.cargo/registry/src/github.com-1ecc6299db9ec823/rafx-api-0.0.10/src/backends/vulkan/buffer.rs:145:30
|
145 |             preferred_flags: vk::MemoryPropertyFlags::empty(),
|                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `ash::vk::bitflags::MemoryPropertyFlags`, found struct `MemoryPropertyFlags`
|
= note: perhaps two different versions of crate `ash` are being used?

error[E0308]: mismatched types
--> /home/cdfa/.cargo/registry/src/github.com-1ecc6299db9ec823/rafx-api-0.0.10/src/backends/vulkan/buffer.rs:159:28
|
159 |             .create_buffer(&buffer_info, &allocation_create_info)
|                            ^^^^^^^^^^^^ expected struct `ash::vk::definitions::BufferCreateInfo`, found struct `BufferCreateInfoBuilder`
|
= note: expected reference `&ash::vk::definitions::BufferCreateInfo`
found reference `&BufferCreateInfoBuilder<'_>`

error[E0308]: mismatched types
--> /home/cdfa/.cargo/registry/src/github.com-1ecc6299db9ec823/rafx-api-0.0.10/src/backends/vulkan/buffer.rs:165:42
|
165 |         let buffer_raw = RafxBufferRaw { buffer, allocation };
|                                          ^^^^^^ expected struct `Buffer`, found struct `ash::vk::definitions::Buffer`
|
= note: perhaps two different versions of crate `ash` are being used?

error[E0308]: mismatched types
--> /home/cdfa/.cargo/registry/src/github.com-1ecc6299db9ec823/rafx-api-0.0.10/src/backends/vulkan/buffer.rs:265:33
|
265 |                 .destroy_buffer(buffer_raw.buffer, &buffer_raw.allocation)
|                                 ^^^^^^^^^^^^^^^^^ expected struct `ash::vk::definitions::Buffer`, found struct `Buffer`
|
= note: perhaps two different versions of crate `ash` are being used?

error: aborting due to 13 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `rafx-api`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

</details>

The issue persists with both the sdl and winit examples :(
I ran the rafx demo with `rafx-vulkan` and had the same problem. Trying `rafx-metal` gave more compiler errors:

<details>
<summary>Log</summary>

```
$ cargo run --bin demo --release --features rafx-metal
...
The following warnings were emitted during compilation:

warning: cc: fatal error: cannot execute ‘cc1obj’: execvp: No such file or directory
warning: compilation terminated.

error: failed to run custom build command for `objc_exception v0.1.2`

Caused by:
process didn't exit successfully: `/home/data/Users/colin/inactive-projects/rafx/target/release/build/objc_exception-d10855f3b65178f6/build-script-build` (exit code: 1)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")
CARGO_CFG_TARGET_FEATURE = Some("aes,avx,avx2,bmi1,bmi2,fma,fxsr,lzcnt,pclmulqdq,popcnt,rdrand,rdseed,sse,sse2,sse3,sse4.1,sse4.2,ssse3,xsave,xsavec,xsaveopt,xsaves")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-o" "/home/data/Users/colin/inactive-projects/rafx/target/release/build/objc_exception-5fe81a9b91f3e19f/out/extern/exception.o" "-c" "extern/exception.m"
cargo:warning=cc: fatal error: cannot execute ‘cc1obj’: execvp: No such file or directory
cargo:warning=compilation terminated.
exit code: 1

--- stderr


error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-o" "/home/data/Users/colin/inactive-projects/rafx/target/release/build/objc_exception-5fe81a9b91f3e19f/out/extern/exception.o" "-c" "extern/exception.m" with args "cc" did not execute successfully (status code exit code: 1).


warning: build failed, waiting for other jobs to finish...
error: build failed
```

</details>

**Comment by aclysma** [comment] 2021-03-15 05:50
**Building skulpin**: I published skulpin 0.13 yesterday which hopefully fixes this. (A new version of an upstream crate was published a few days ago). You could also try running cargo update. If it's still broken, cargo tree will print out the dependency tree which can be used to figure out what crates are pulling in different versions of the same crate. CI is passing though so I suspect if you have the latest and run `cargo update`, it will build.

**Testing with rafx demo**: I assume "same problem" with rafx demo means you were able to build/run but it was stuck after suspending/resuming. I'll set up a rafx branch with all logging turned on - that might help track this down. (btw "rafx-metal" is macOS only so it's expected that one did not build on linux). Hoping I can get to this in the next few days. Thanks for the patience!

**Comment by cdfa** [comment] 2021-03-15 09:28
The build is fixed! I forgot to mention: I checked the sdl and winit examples using one commit before the one i was having issues with last time.

> I assume "same problem" with rafx demo means you were able to build/run but it was stuck after suspending/resuming.

Correct.

> (btw "rafx-metal" is macOS only so it's expected that one did not build on linux)

Ahh, makes sense :)

Looking forward to the debugging branch. Thanks for your help!

**Comment by aclysma** [comment] 2021-03-18 05:13
I've added a branch "logging-for-suspend-bug" to rafx at https://github.com/aclysma/rafx.git

```
git clone -b logging-for-suspend-bug https://github.com/aclysma/rafx.git
cd rafx/rafx
cargo run --example api_triangle --features="rafx-vulkan"
```

Hopefully that builds and runs. This will grab a log
```
cargo run --example api_triangle --features="rafx-vulkan" &> out.txt
```

If you could run that, reproduce, and send out.txt, I think I can figure out where it's getting stuck.

**Comment by cdfa** [comment] 2021-03-18 08:54
Alright, I got it! [out.zip](https://github.com/aclysma/skulpin/files/6162520/out.zip)
When I run it in the terminal, it repeatedly shows the last few lines of the "cycle", so it seems most time is spent "between cycles". The cycle also ended on the same lines a second time I ran it. Could this be a VSYNC thing?

I'm beginning to wonder if it's not just my setup. There was also a game that would get stuck in a similar fashion after suspend and resume, but I always thought that it was because of some weird linux+nvidia issue, because it was using my laptops dedicated GPU (these examples should not be). I also tried to run the examples with the dedicated GPU, but it doesn't make a difference.

**Comment by cdfa** [comment] 2021-03-18 12:50
And then I forgot the whole reason for the second paragraph (of my previous comment): do you know of any application or library that works similar to skulpin, but which should definitely work. If it does not, we'll know my setup is the problem.

**Comment by aclysma** [comment] 2021-03-18 15:12
I added more logging. In particular I want to confirm if the call to vkQueuePresentKHR() is never returning. Could you try again with latest code on that branch? And just to make sure I understand, you're closing the laptop lid making the machine sleep? And if you run it without the `&> out.txt`, it is not spamming anything after you resume? And something like `[2021-03-18T08:41:41.601778353Z TRACE rafx_api::backends::vulkan::queue] present to dedicated present queue 0x562f8d5cc978` is always the last line?

The Vulkan SDK ships with an example "vkcube" that is frequently used to verify vulkan is working, but I don't know if/where that would be on linux.

**Comment by cdfa** [comment] 2021-03-23 10:16
I tested with `vkcube` and the same is happening, so it does not seems to be a skulpin issue. I created a forum post [here](https://forum.manjaro.org/t/applications-running-on-gpu-stuck-after-resume/59303). Thanks a lot for your help and feel free to close :)

**Closed as completed** 2021-03-27 21:29 UTC
