### ISSUE TITLE
Resolve of vkGetImageMemoryRequirements2 failed (Linux)

### ISSUE THREAD

**Issue by cout970** [aclysma/skulpin#14] opened 2019-11-06 18:55 UTC
I was trying the examples but none of them work, they compile but crash at line 45 in src/renderer/skia_support.rs
```
let context = skia_safe::gpu::Context::new_vulkan(&backend_context).unwrap();

VkSkiaContext {
     context
}
```
I was expecting some king of error message, I have up to date vulkan drivers and I run Manjaro (Linux 5.3.6-1 kernel) with a Nvidia GTX1050 Ti.

This is the crashlog: https://pastebin.com/7aHgHjMa

**Comment by aclysma** [comment] 2019-11-06 19:55
Thanks for taking the time to report this. Looks a lot like #13 (skia is asking for vulkan 1.1 APIs), so it’s very useful to know someone else is hitting it, and on a different platform. There’s some info in a comment I added last night that might be relevant.

**Comment by aclysma** [comment] 2019-11-22 05:32
Does this change help by chance? Unfortunately since I can't reproduce this, I don't have a good way to know if this fix works or not. https://github.com/aclysma/skulpin/commit/e6869f22c0c7d2ee8797ec01761e2ecf5efcb3f6

**Comment by cout970** [comment] 2019-11-22 14:42
I tested it and now it crashes in another way, this is the log https://pastebin.com/u7eMt01C
The program itself doesn't crash, I have to manually kill it because freezes the screen for a few seconds, then stops for 1 seconds and the freezes again.


Also `Calculated physical dimensions: 1350x900` is wrong, my display is 2560x1440, and I have 2 monitors, both with the same resolution.

**Comment by aclysma** [comment] 2019-11-22 14:53
Nice, thanks for checking! The resolution is expected because the examples should be 900x600 logical size and the app detected a 1.5x dpi factor. I see a lot of validation errors in the log you pasted which is very helpful. Hopefully can have a fix for this very soon.

**Comment by aclysma** [comment] 2019-11-23 06:30
Thanks again for the info. I think https://github.com/aclysma/skulpin/commit/fb01ea685414ba698b81f80315bcda4daa6f1616 will help out. I had bad logic in the queue family selection. I suspect that your hardware looks like this https://vulkan.gpuinfo.org/displayreport.php?id=6772#queuefamilies and it picked QF 0 for graphics and QF 2 for presentation. It needed to use QF 0 for both.

I also added more logging for queue family handling so if it still isn't working for you, there will hopefully be more info on the next try.

Again, huge thanks!

**Comment by cout970** [comment] 2019-11-23 13:57
It works perfectly now, thanks for fixing the bug.

I have plans to use this library for a project, but I need to finish other projects first and that will take weeks or months. 

Anyway thanks for your hard work, keep it going!

**Closed as completed** 2019-11-23 15:07 UTC
