### ISSUE TITLE
Unable to build on Linux with nightly

### ISSUE THREAD

**Issue by osa1** [aclysma/skulpin#38] opened 2020-01-29 10:23 UTC
I can build with just `cargo build`, but if I try to run an example or run the tests with `cargo test` I get this:

```
$ cargo test
   Compiling matrixmultiply v0.2.3
   Compiling generic-array v0.12.3
   Compiling alga v0.9.2
   Compiling num-rational v0.2.3
error: array lengths can't depend on generic parameters
   --> /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.2.3/src/sgemm_kernel.rs:223:40
    |
223 |     let mut ab = [_mm256_setzero_ps(); MR];
    |                                        ^^

error: array lengths can't depend on generic parameters
   --> /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.2.3/src/sgemm_kernel.rs:418:40
    |
418 |     let mut cv = [_mm256_setzero_ps(); MR];
    |                                        ^^

error: array lengths can't depend on generic parameters
   --> /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.2.3/src/sgemm_kernel.rs:473:44
    |
473 |     let mut ab: [[T; NR]; MR] = [[0.; NR]; MR];
    |                                            ^^

error: array lengths can't depend on generic parameters
   --> /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.2.3/src/sgemm_kernel.rs:473:39
    |
473 |     let mut ab: [[T; NR]; MR] = [[0.; NR]; MR];
    |                                       ^^

error: array lengths can't depend on generic parameters
   --> /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.2.3/src/dgemm_kernel.rs:235:40
    |
235 |     let mut ab = [_mm256_setzero_pd(); MR];
    |                                        ^^

error: array lengths can't depend on generic parameters
   --> /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.2.3/src/dgemm_kernel.rs:711:40
    |
711 |     let mut cv = [_mm256_setzero_pd(); MR];
    |                                        ^^

error: array lengths can't depend on generic parameters
   --> /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.2.3/src/dgemm_kernel.rs:786:44
    |
786 |     let mut ab: [[T; NR]; MR] = [[0.; NR]; MR];
    |                                            ^^

error: array lengths can't depend on generic parameters
   --> /home/omer/.cargo/registry/src/github.com-1ecc6299db9ec823/matrixmultiply-0.2.3/src/dgemm_kernel.rs:786:39
    |
786 |     let mut ab: [[T; NR]; MR] = [[0.; NR]; MR];
    |                                       ^^

error: aborting due to 8 previous errors

error: could not compile `matrixmultiply`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

which is surprising because I was able to build another project that uses skulpin using nightly.

**Comment by aclysma** [comment] 2020-01-29 17:37
I would try
 - save a copy of your cargo lock file on both the building and non-building project (or make sure it’s committed and you can revert to it)
 - run cargo update on both
 - see if they still have inconsistent behavior

What gets updated could be a clue. If they both build, then there’s nothing to fix. If they don’t build, it’s likely an upstream issue caused by something not strictly using semver. You could get around this with cargo update -p cratename —precise working.version.number or we could throw a dependency in skulpin temporarily to force it. 

I’ll re-kick the CI also to see if that gives any clues.

**Comment by aclysma** [comment] 2020-03-03 07:17
Going to close as this is passing on CI. Please reopen if you're still having trouble building.

**Closed as completed by aclysma** 2020-03-03 07:17 UTC

**Comment by osa1** [comment] 2020-03-03 07:22
Just tried again and I'm able to build it on Linux using nightly now. Thanks!
