### ISSUE TITLE
New commits causing breaking changes on older versioned skulpins.

### ISSUE THREAD

**Issue by MatthewBlanchard** [aclysma/skulpin#90] opened 2021-03-12 01:19 UTC
https://github.com/aclysma/skulpin/commit/ddc8c339a34792d53d6a4ec427c35f41dbf003d6

This newest commit broke my 0.11.0 build. 

```
error[E0308]: mismatched types
  --> C:\Users\Matt\.cargo\registry\src\github.com-1ecc6299db9ec823\skulpin-renderer-0.5.1\src\skia_support.rs:67:17
   |
61 |     ) -> Option<unsafe extern "system" fn() -> c_void> {
   |          --------------------------------------------- expected `Option<unsafe extern "system" fn() -> c_void>` because of return type
...
67 |                 instance.entry.get_instance_proc_addr(ash_instance, name)
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `c_void`, found `()`
   |
   = note: expected enum `Option<unsafe extern "system" fn() -> c_void>`
              found enum `Option<unsafe extern "system" fn()>`

error[E0308]: mismatched types
  --> C:\Users\Matt\.cargo\registry\src\github.com-1ecc6299db9ec823\skulpin-renderer-0.5.1\src\skia_support.rs:71:17
   |
61 |     ) -> Option<unsafe extern "system" fn() -> c_void> {
   |          --------------------------------------------- expected `Option<unsafe extern "system" fn() -> c_void>` because of return type
...
71 |                 instance.instance.get_device_proc_addr(ash_device, name)
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `c_void`, found `()`
   |
   = note: expected enum `Option<unsafe extern "system" fn() -> c_void>`
              found enum `Option<unsafe extern "system" fn()>`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `skulpin-renderer`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error[E0308]: mismatched types
  --> C:\Users\Matt\.cargo\registry\src\github.com-1ecc6299db9ec823\skulpin-renderer-0.4.1\src\skia_support.rs:67:17
   |
61 |     ) -> Option<unsafe extern "system" fn() -> c_void> {
   |          --------------------------------------------- expected `Option<unsafe extern "system" fn() -> c_void>` because of return type
...
67 |                 instance.entry.get_instance_proc_addr(ash_instance, name)
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `c_void`, found `()`
   |
   = note: expected enum `Option<unsafe extern "system" fn() -> c_void>`
              found enum `Option<unsafe extern "system" fn()>`

error[E0308]: mismatched types
  --> C:\Users\Matt\.cargo\registry\src\github.com-1ecc6299db9ec823\skulpin-renderer-0.4.1\src\skia_support.rs:71:17
   |
61 |     ) -> Option<unsafe extern "system" fn() -> c_void> {
   |          --------------------------------------------- expected `Option<unsafe extern "system" fn() -> c_void>` because of return type
...
71 |                 instance.instance.get_device_proc_addr(ash_device, name)
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `c_void`, found `()`
   |
   = note: expected enum `Option<unsafe extern "system" fn() -> c_void>`
              found enum `Option<unsafe extern "system" fn()>`
```

I'm not sure why these changes are affecting previous versions, but each time I've cargo clean'd and been presented with new build errors. 

```
skulpin = { version = "0.11.2", default-features = false, features = ["skia_complete", "skulpin_winit", "winit-22"] }
skulpin-plugin-imgui = { version = "0.7.1" }
imgui-winit-support = "0.5.0"
```
 Seems tied to when you update Skia versions?

**Comment by aclysma** [comment] 2021-03-12 08:34
This is a dupe of #89. It’s caused by an upstream release of ash and a workaround is described in that issue. I may try backporting the fix to 0.11 so I’ll leave this open for now

**Comment by aclysma** [comment] 2021-03-14 04:34
I published 0.11.3 to fix this. Running cargo update should clear the errors.

Also, just wanted to mention, you said "This newest commit broke my 0.11.0 build." Assuming you're pulling skulpin in by version and not by git URL, commits in the repo can't affect your build. What likely happened is `cargo update` was run (maybe explicitly by you, maybe implicitly by some other cargo action.) A new version of a non-skulpin crate (ash) was available and downloaded, and this crate was not compatible with skulpin. The timing of the git commit is likely circumstantial. What this fix does is force cargo not to use versions of ash >= 0.32

**Closed as completed by aclysma** 2021-03-14 04:34 UTC
